#!/bin/bash

set -o errexit

trace () {
    echo "Running:" $*
    $*
}

for file in $(find . -name .git -prune -o -print); do
    [ "$file" = "$0" ] && continue
    [ "$file" = "." ] && continue

    # target is in ~/ with an extra "." before.
    # We also must strip the leading "./" find adds.
    target=~/.${file#./}

    # Skip any already-existing directories.
    [ -d $target ] && continue
    # Create any necessary directories.
    if [ -d $file ]; then
	trace mkdir -p $target
	continue
    fi

    if [ -e $target ]; then
	# -ef tests whether they're sharing a hardlink.
	if [ ! "$file" -ef "$target" ]; then
	    echo "Skipping local $target; delete if unintentionally local."
	fi
	continue
    fi
    trace ln $file $target
done