#!/bin/bash

set -o errexit

trace () {
    echo "Running:" $*
    $*
}

pwd=$(pwd)
for file in *; do
    [ "$file" = "config" ] && continue
    [ "$file" = "." ] && continue

    target=~/.$file

    if [ -e $target ]; then
        link=$(readlink $target || echo)
        if [ "${link%/}" != $pwd/$file ]; then
            echo "Skipping $target -- remove it if it should be managed by config."
        fi
        continue
    fi
    trace ln -s $pwd/$file $target
done
