#!/bin/bash

set -o errexit

trace () {
    echo "Running:" $*
    $*
}

link() {
    file=$1
    target=~/.$file

    if [ -e $target ]; then
        link=$(readlink $target || echo)
        if [ "${link%/}" != $pwd/$file ]; then
            echo "Skipping $target -- remove it if it should be managed by config."
        fi
        continue
    fi
    trace ln -s $pwd/$file $target
}

pwd=$(pwd)
for file in *; do
    [ "$file" = "link-config" ] && continue
    [ "$file" = "local" ] && continue
    [ "$file" = "." ] && continue

    link $file
done

for dir in $(find local -type d); do
    mkdir -p ~/.$dir
done
for file in $(find local -type f); do
    link $file
done
